### ISSUE TITLE
Support for keyword, USE and mask files

### ISSUE THREAD

**Issue by fusion809** [aegypius/language-gentoo#3]
Hi,

This isn't an issue so much I was just wondering if you have any intention to add syntax highlighting support for keyword, USE, mask and conf files as these are important files too for Gentoo users and developers alike. 

Thanks for your time,
Brenton

**Comment by aegypius** [comment]
This is actually a great idea, even if it may not work if you use the directory based use/keyword files (like I do). I will try to update this addon with a basic support for `use` and `keywords` files

**Comment by aegypius** [comment]
Hi @fusion809, 

I don't know if you still using the language-gentoo package for atom. I just released a new version with a basic `use` and `keywords` support. Feel free to give it a try and give me your feedback !
